name: form_state
description: Lightweight reactive form framework. Cleanly separate form logic from the UI.
version: 0.0.2
repository: https://github.com/olaleyeone/form_state

environment:
  sdk: ">=2.1.0 <3.0.0"